sudo: required
services:
  - docker
before_install:
  - docker build -t kosac-dev/kube-api-server -f Dockerfile.dev .
script:
  - docker run kosac-dev/kube-api-server npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "seoul"
  app: "Defora"
  env: "Defora-env"
  bucket_name: "elasticbeanstalk-seoul-sldkfjsd"
  bucket_path: "Defora"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"