version: '3'
services:
  mongoDB:
    image: 'mongo'
    container_name: 'mongo-database'
  redis:
    image: 'redis'
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  graphqlserver:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./graphql-mongo-api
  websocket:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./websocket