version: '3'
services:
  mongoDB:
    image: 'mongo'
    container_name: 'mongo-database'
  redis:
    image: 'redis'
    container_name: 'redis-server'
  nginx:
    container_name: 'nginx-server'
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    container_name: 'api-server'
    build:
      context: ./api
      dockerfile: Dockerfile.dev
  client:
    container_name: 'client'
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  graphqlserver:
    container_name: graphqlserver
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./graphql-mongo-api
  websocket:
    container_name: 'websocket'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./websocket